title: Stonks Pro

description: Go from Stinks to Stonks.
baseurl: ""

username: S.t.o.n.k.s. Pro
typing_text: From the School of Markets
email: schoolofmarkets@gmail.com
twitter_username: school.of.markets

show_aboutme_card: true

about_me_title: What the fuck is a stonks pro?

about_me_description: <p style="color:red"> This is the unapologetic, expelitive-rich program where people have learnt some nitty-gritties of trading any security - stocks, commodities, currencies and cryptos.</p><br><p><i>"In the recent times, I've seen some of the thousands of self-proclaimed experts out there who sell Stock Tips/Calls/Ideas with 90% (or even above lol!) accuracy, for shitloads of money. If you always ask "the guy" for tips, calls and trades, and just do what he says, i mean, you can as well cut off your balls with a rusted blade."</i></p><br><h3> Have balls, take your own calls.</h3><p> Stonks is here for that. The idea of this course is to give you the know-how, the cumulative experiential learnings of thousands of trades and several good and bad traders and investors so that you know what the fuck you're supposed to do. Choose Stonk, not Stink.</p> <br><p style="color:red"> A funny fact is that, only 1% of active traders beat FD returns, and everyone thinks they're in that 1%!</p>
show_skills_card: true

skills_title: Some of the stuff you'll get in Stonks Pro
show_timeline_card: true

timeline_title: The Stonks timeline
cv_download_link: https://rzp.io/l/SMMCpro

show_projects_card: true
show_projects: true

projects_title: What some dudes have said after completing the effin course<br><p style="font-size:12px">I mean, when the course is good, even normal reviews seem like paid. That's why i've added a paid review i purchased alongwith the other genuine ones.</p>
show_os_projects: false
os_projects_title:

show_contact_card: true
contact_title: <a href="https://rzp.io/l/SMMCpro">Fucking get the course here.</a> And, if you're not yet convinced... Get in touch here pussy! (No. No touchy touchy stuff)
contact_description: Send a mail <a href ="mailto:schoolofmarkets@gmail.com">here</a> Get in touch on Whatsapp <a href="https://wa.me/919884140499">here</a> <br>
    <h3>FAQs</h3>
    <ul>
    <li><h4 style="color:red">Do I "have" to get this?</h4><p>You can. There is no "Have to". It's just like cleaning your butt after taking a shit. You "can". You don't "have to".</p>
    </li>
    <li><h4 style="color:red">Is there any free trial?</h4><p>Nope. As much as I love to get stuff for free, knowledge like a whore, is better when paid for.</p>
    </li>
    <li><h4 style="color:red">Will I be able to make sure-shot profits after this?</h4><p>This course will give you the know-how to avoid treading losses, but, as they say, even the thickest condom is only 97% effective.</p>
    </li>
    <li><h4 style="color:red">I'm a beginner to trading. Will this help me?</h4><p>Congrats! You're a Virgin. It'll<i>(learning)</i> come faster.</p>
    </li>
    <li><h4 style="color:red">How will the course be given?</h4><p>That's a tricky one. There is Video On Demand option with doubts clearing every weekend, live-streaming of classes (rarely, because, each one of us has a different 'max-productive' time), and if you want a live one-one session, get in touch. It can be made possible.<br><br> <i>If you can't make a decision, Think of it like this - It is the difference between going to Pornhub and looking up a video, or, paying more on onlyfans to get a customised video for a group, or, going the max simp way, and getting a custom one-one livestream from a cam-girl.</i></p>
    </li>
    <li><h4 style="color:red">Will the course also have all these cuss words? I need to show this to my mom.</h4><p><i>"Um..."</i></p>
    </li>
    <li><h4 style="color:red">What's the price of the course?</h4><p>Pricing might change in currency from (USD/INR/EUR/GBP/JPY/CAD/BTC/ETH) time to time. To see fee for your region, click on the buy link, it'll open up the relevant payment gateway.</p>
    </li>
    <li><h4 style="color:red">If I need a custom course, can I get in touch?</h4><p>Mail would be appreciated, a text on Whatsapp would be convinient, a call would be as uncomfortable as a premature ejaculation in the pants.</p>
    </li></ul>
plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
