title: Stonks Pro

description: Go from Stinks to Stonks.
baseurl: ""

username: S.t.o.n.k.s. Pro
typing_text: From the School of Markets
email: schoolofmarkets@gmail.com
twitter_username: school.of.markets

show_aboutme_card: true

about_me_title: Oh fuck, another Guy with a course?

about_me_description: Firstly, it's 2021, don't assume my gender. <p style="color:red">And, secondly, I idenfity as a <em><b>Fucking "Panzerkampfwagen"</b></em></p> <i>(If you don't know what it means, may hitler's soul bless mercy on your incompetence)</i><br><p>The truth is that tere are just too many guys out there who sell Stock Tips/Calls/Ideas for shitloads of money. If you always ask "the guy" for tips, calls and trades, and just do what he says, i mean, you can as well cut off your balls with a rusted blade.</p><br><h3> Have balls, take your own calls.</h3><p> Stonks is here for that. The idea is to give you the know-how and the cumulative experiential learnings of several good and bad traders and investors so that you know what the fuck you're supposed to do. Choose Stonk, not Stink.</p>
show_skills_card: true

skills_title: Some of the stuff you'll get in Stonks Pro
show_timeline_card: true

timeline_title: The Stonks timeline
cv_download_link: https://rzp.io/l/SMMCpro

show_projects_card: true
show_projects: true

projects_title: What some dudes have said after completing the effin course<br><p style="font-size:12px">I mean, when the course is good, even normal reviews seem like paid. That's why i've added a paid review i purchased alongwith the other genuine ones.</p>
show_os_projects: false
os_projects_title: Open Source Projects

show_contact_card: true
contact_title: <a href="https://rzp.io/l/SMMCpro">Fucking get the course here.</a> And, if you're not yet convinced... Get in touch here pussy! (No. No touchy touchy stuff)
contact_description: Send a mail <a href ="mailto:schoolofmarkets@gmail.com">here</a> Get in touch on Whatsapp <a href="https://wa.me/919884140499">here</a> <br>
    <h3>FAQs</h3>
    <p>

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
